config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'orders/index'
    get 'orders/show'
  end
#public/cart_itemのアクションを追加した===================================
  namespace :public do
    resources :cart_items, only: [:index, :create, :update, :destroy] do
        collection do
            delete 'destroy_all'
        end
    end
  end
  #=======================================================================
  devise_for :customers
   namespace :public do
   resources :customers, only: [:show,:update,:index] do
       collection do
        get :edit
        get 'unsubscribe'
        patch "withdrawal"
       end
   end
 end

 devise_for :admins, controllers: {
  sessions: 'admin/sessions'
}

  namespace :admin do
    resources :customers, only: [:index,:show,:edit,:update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 namespace :public do
  resources :deliveries, only: [:create, :index, :edit, :update, :destroy]
  get 'about' => 'homes#about'
   resources :items, only: [:index, :show]
 end
 root to: 'public/homes#top'
   # 会員側のルーティング設定

  # 管理者側のルーティング設定
  namespace :admin do
    resources :items, only: [:index, :show, :new, :create, :edit, :update]
    resources :genre, only: [:index, :edit, :create, :update]
    resources :order_details, only: [:update]
  end

 namespace :public do
     resources :orders, only: [:index, :show, :new, :create]
      get 'log' => 'orders#log'

     post 'log' => 'orders#log'

     get 'thanks' => 'orders#thanks'
    end

   namespace :admin do
     resources :orders, only: [:show, :update, :index]
   end
end

app/models/item.rb
class Item < ApplicationRecord

    #従属しているモデル====================
    has_many :cart_items , dependent: :destroy
    belongs_to :genre, optional: true
    #======================================

    #画像==================================
    attachment :image
    #======================================

    # enumの設定===========================
    enum status: {販売中:0, 販売停止中:1}
    #======================================

    #バリデーションの追加==================
    validates :name, presence: true
    validates :image, presence: true
    validates :introduction, presence: true
    validates :price, presence: true
    validates :is_active, inclusion:{in: [true, false]}
    # boolean型は「presence: true」と定義すると、false =「nil」と認識されるので
    #「inclusion:{in:[true,false]}で「true」と「false」の両方を認識させる 
    #======================================

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    def new
        #新規アイテムの追加
        @item = Item.new

    end
    def create
        #@itemの定義
        @item = Item.new(item_params)

        if @item.save #登録出来たら============================================
            redirect_to admin_item_path(@item.id), success: "新商品を追加しました。"
        else #登録できなかったら===============================================
            @items = Item.page(params[:page]).reverse_order
            render 'index', danger: "登録失敗しました"
        end
    end
    def index
        #ページング機能の追加=========================
        @items = Item.page(params[:page])
        #=============================================

    end

    def show
        #アイテムのidを参照して指定された商品詳細を表示
        @item = Item.find(params[:id])

    end

    def edit
        #アイテムのidを参照して指定された商品詳細を表示
        @item = Item.find(params[:id])
    end
    def update
        @item = Item.find(params[:id])
        if @item.update(item_params)
            redirect_to admin_item_path(@item.id)
        else
            render 'edit'
        end
    end

    private
    def item_params
        params.require(:item).permit(:genre_id, :name, :price, :is_active, :introduction, :image)
    end

end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/views/admin/items/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="title">
                <h3 style="background-color:#eeeeee;">商品編集</h3>
            </div>    
            <div class="new-item">
                <%= form_with(model: @item, url:admin_item_path(@item.id)) do |f| %>
                <table class="new-item-table">
                    <tr>
                        <td>商品画像</td>
                        <td><%= f.attachment_field :image %></td>
                    </tr>
                    <tr>
                        <td>商品名</td>
                        <td><%= f.text_field :name %></td>
                    </tr>
                    <tr>
                        <td>商品説明</td>
                        <td><%= f.text_area :introduction %></td>
                    </tr>
                    <tr>
                        <td>ジャンル</td>
                        <td><%= f.collection_select :genre_id, Genre.all, :id, :name, {:include_blank => "-選択してください-"} %></td>
                    </tr>
                    <tr>
                        <td>税抜価格</td>
                        <td><%= f.text_field :price %>円</td>
                    </tr>
                    <tr>
                        <td>販売ステータス</td>
                        <td>
                            <%= f.radio_button :is_active, :true %>
                            <%= f.label :is_active, "販売中",value: :true, style: "display: inline-block;" %>
                            <%= f.radio_button :is_active, :false %>
                            <%= f.label :is_active, "販売停止中",value: :false, style: "display: inline-block;" %>
                        </td>
                    </tr>
                </table>
                <%= f.submit "変更を保存", class: 'btn btn-success' %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/admin/items/index.html.erb
<div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="title">
          <h2>商品一覧</h2>
        </div>
        <div class="add-item" style="display:right">
          <%= link_to '',new_admin_item_path, class: "fas fa-plus fa-2x" %>
        </div>
        <table class='table table-bordered table-hober table-inverse'>
          <thead class="table-active">
            <th class="border-dark">商品ID</th>
            <th class="border-dark">商品名</th>
            <th class="border-dark">税抜価格</th>
            <th class="border-dark">ジャンル</th>
            <th class="border-dark">ステータス</th>
          </thead>
          <tbody　class="table-borderless">
            <% @items.each do |item| %>
              <tr>
                <td class="border-dark"><%= item.id %></td>
                <td class="border-dark"><%= link_to item.name, admin_item_path(item.id) %></td>
                <td class="border-dark"><%= item.price %></td>
                <td class="border-dark"><%= item.genre.name %></td>
                <td class="border-dark">
                  <% if item.is_active == true %>
                    <p style="color:green; font-weight:bold;"><%= "販売中" %></p>
                  <% else %>
                    <p style="color:gray; font-weight:bold"><%= "販売停止中" %></p>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <div class="paging">
          <%= paginate @items %>
        </div>
      </div>
    </div>
</div>

app/views/admin/items/new.html.erb
<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <div class="title">
                <h2 style="background-color:#eeeeee;">商品新規登録</h2>
            </div>
            <br />
            <div class="new-item">
                <%= form_with(model: @item, url:admin_items_path) do |f| %>
                <table class="new-item-table">
                    <tr>
                        <td>商品画像</td>
                        <td><%= f.attachment_field :image %></td>
                    </tr>
                    <tr>
                        <td>商品名</td>
                        <td><%= f.text_field :name %></td>
                    </tr>
                    <tr>
                        <td>商品説明</td>
                        <td><%= f.text_area :introduction %></td>
                    </tr>
                    <tr>
                        <td>ジャンル</td>
                        <td><%= f.collection_select :genre_id, Genre.all, :id, :name, {:include_blank => "-選択してください-"} %></td>
                    </tr>
                    <tr>
                        <td>税抜価格</td>
                        <td><%= f.text_field :price %>円</td>
                    </tr>
                    <tr>
                        <td>販売ステータス</td>
                        <td>
                            <%= f.radio_button :is_active, :true %>
                            <%= f.label :is_active, "販売中",{value: :true, style: "display: inline-block;"} %>
                            <%= f.radio_button :is_active, :false %>
                            <%= f.label :is_active, "販売停止中",{value: :false, style: "display: inline-block;"} %>
                        </td>
                    </tr>
                </table>
                <div class="submit-item" style="text-align:center">
                    <%= f.submit "新規登録", class: 'btn btn-success' %>
                </div>
                
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/admin/items/show.html.erb
<div class="container">
    <div class="title">
        <h3>商品詳細</h3>
    </div>

    <div class="row">

        <div class="col-lg-4">
            <%= attachment_image_tag @item, :image, width:"200" ,fallback: "no_image.jpg" %>
        </div>
        <div class="col-lg-8">
            <table class='table table-hover table-inverse'>
                <tr>
                    <td>商品名</td>
                    <td><%= @item.name %></td>
                </tr>
                <tr>
                    <td>商品説明</td>
                    <td><%= @item.introduction %></td>
                </tr>
                <tr>
                    <td>ジャンル</td>
                    <td><%= @item.genre.name%></td>
                </tr>
                <tr>
                    <td>税込価格<br />(税抜価格)</td>
                    <td><%= (@item.price*1.1).floor %>(<%= @item.price %>)円</td><!--税込み価格を記載のこと-->
                </tr>
                <tr>
                    <td>販売ステータス</td>
                    <td>
                        <% if @item.is_active == true %>
                            <p style="color:green"><%= "販売中" %></p>
                        <% else %>
                            <p style="color:gray"><%= "販売停止中" %></p>
                        <% end %>
                    </td>
                </tr>
            </table>
        </div>
        <div class="pl-4">
            <%= link_to '編集する', edit_admin_item_path(@item.id), class: "btn btn-success" %>
        </div>
    </div>
</div>