config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'orders/index'
    get 'orders/show'
  end
#public/cart_itemのアクションを追加した===================================
  namespace :public do
    resources :cart_items, only: [:index, :create, :update, :destroy] do
        collection do
            delete 'destroy_all'
        end
    end
  end
  #=======================================================================
  devise_for :customers
   namespace :public do
   resources :customers, only: [:show,:update,:index] do
       collection do
        get :edit
        get 'unsubscribe'
        patch "withdrawal"
       end
   end
 end

 devise_for :admins, controllers: {
  sessions: 'admin/sessions'
}

  namespace :admin do
    resources :customers, only: [:index,:show,:edit,:update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 namespace :public do
  resources :deliveries, only: [:create, :index, :edit, :update, :destroy]
  get 'about' => 'homes#about'
   resources :items, only: [:index, :show]
 end
 root to: 'public/homes#top'
   # 会員側のルーティング設定

  # 管理者側のルーティング設定
  namespace :admin do
    resources :items, only: [:index, :show, :new, :create, :edit, :update]
    resources :genre, only: [:index, :edit, :create, :update]
    resources :order_details, only: [:update]
  end

 namespace :public do
     resources :orders, only: [:index, :show, :new, :create]
      get 'log' => 'orders#log'

     post 'log' => 'orders#log'

     get 'thanks' => 'orders#thanks'
    end

   namespace :admin do
     resources :orders, only: [:show, :update, :index]
   end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

    has_many :cart_items
    has_many :orders
    has_many :deliveries

    def active_for_authentication?
        super && (self.withdrawal == false)
    end
    #is_activeが有効の場合は有効会員(ログイン可能)
end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
  	@customers = Customer.page(params[:page]).per(10)
  end

	def show
		@customer = Customer.find(params[:id])
	end

	def edit
		@customer = Customer.find(params[:id])
	end

	def update
	@customer = Customer.find(params[:id])
		if @customer.update(customer_params)
		   flash[:success] = "会員情報を変更しました"
		   redirect_to admin_customer_path
		else
			render "edit"
		end

	end

	private
	def customer_params
	  params.require(:customer).permit(
	  	:first_name,
	  	:last_name,
	  	:first_name_kana,
	  	:last_name_kana,
	  	:address,
	  	:address_number,
	  	:phone_number,
	  	:email,
	  	:withdrawal)
	end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.html.erb
<br>
<div class="container">
  <div class="row">
    <h4 class = bg-light><%= @customer.last_name %><%= @customer.first_name %>さんの会員情報編集</h4>
  </div>
</div>

<%= form_with model:@customer,url: admin_customer_path(@customer.id), local:true do |f| %>
<div class="container">
  <div class="row">
    <table>
      <tbody>

          <tr>
            <th>会員ID</th>
            <td ><%= @customer.id %></td>
          </tr>
          <tr>
            <th>氏名</th>
            <td><%= f.text_field :last_name %></td>
            <td><%= f.text_field :first_name %></td>
          </tr>
          <br>
          <tr>
            <th>フリガナ</th>
            <td><%= f.text_field :last_name_kana %></td>
            <td><%= f.text_field :first_name_kana %></td>
          </tr>

          <tr>
            <th>郵便番号</th>
            <td><%= f.text_field :address_number %></td>
          </tr>
          <tr>
            <th>住所</th>
            <td><%= f.text_field :address %></td>
          </tr>
          <tr>
            <th>電話番号</th>
            <td><%= f.telephone_field :telephone_number %></td>
          </tr>
          <tr>
            <th>メールアドレス</th>
            <td><%= f.text_field :email %></td>
          </tr>
          <tr>
            <th>会員ステータス</th>
            <td>
              <%= f.radio_button :withdrawal, false %>
              <%= f.label :is_deleted, "有効", value: false %>
            </td>
            <td>
              <%= f.radio_button :withdrawal, true %>
              <%= f.label :withdrawal, "退会", value: true %>
            </td>
          </tr>

  <div class="container">
    <div class="row">
        <tr>
          <th><div class = bg-center ><%= f.submit '変更を保存',class: "btn btn-primary"%></div></th>
        </tr>
      <% end %>
    </tbody>
   </table>
  </div>
</div>

app/views/admin/customers/index.html.erb
<div class="container">
  <div class="admin-customer pt-5">
    <h4 class="pb-3">会員一覧</h4>
    <table class="table table-bordered table-hober table-inverse">
      <tr class="table-active">
        <th class="border-dark">会員ID</th>
        <th class="border-dark">氏名</th>
        <th class="border-dark">メールアドレス</th>
        <th class="border-dark">ステータス</th>
      </tr>
      <% @customers.each do |customer| %>
        <tr>
          <td class="border-dark">
            <%= customer.id %>
          </td>
          <td class="border-dark">
            <%= link_to customer.last_name+" "+customer.first_name, admin_customer_path(customer), class: "text-dark" %>
          </td>
          <td class="border-dark">
            <%= customer.email %>
          </td>
          <td class="border-dark">
            <% if customer.withdrawal == true %>
              <p class="text-secondary">退会済</p>
            <% else %>
              <p class="text-success">有効</p>
            <% end %>
          </td>
        </tr>
      <% end %>
      </table>
    <div class="pagenate">
      <%= paginate @customers %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container">
  <div class="admin-customer-show pt-5">
    <h4 class="pb-3"><%= @customer.last_name+" "+@customer.first_name %>さんの会員詳細</h4>
    <table class="w-100 admin-customer-show">
      <tr class="row pb-3">
        <td class="col-md-2">会員ID</td>
        <td class="col-md-10"><%= @customer.id %></td>
      </tr>
      <tr class="row pb-3">
        <td class="col-md-2">氏名</td>
        <td class="col-md-10"><%= @customer.last_name+" "+@customer.first_name %></td>
      </tr>
      <tr class="row pb-3">
        <td class="col-md-2">フリガナ</td>
        <td class="col-md-10"><%= @customer.last_name_kana+" "+@customer.first_name_kana %></td>
      </tr>
      <tr class="row pb-3">
        <td class="col-md-2">郵便番号</td>
        <td class="col-md-10"><%= @customer.address_number %></td>
      </tr>
      <tr class="row pb-3">
        <td class="col-md-2">住所</td>
        <td class="col-md-10"><%= @customer.address %></td>
      </tr>
      <tr class="row pb-3">
        <td class="col-md-2">電話番号</td>
        <td class="col-md-10"><%= @customer.phone_number %></td>
      </tr>
      <tr class="row pb-3">
        <td class="col-md-2">メールアドレス</td>
        <td class="col-md-10"><%= @customer.email %></td>
      </tr>
      <tr class="row pb-3">
        <td class="col-md-2">会員ステータス</td>
        <td class="col-md-10">
          <% if @customer.withdrawal == true %>
            <p class="text-secondary">退会済</p>
          <% else %>
            <p class="text-success">有効</p>
          <% end %>
        </td>
      </tr>
      <tr class="row">
        <td class="col-md-2"></td>
        <td class="col-md-10">
          <%= link_to "編集する", edit_admin_customer_path(@customer), class: "btn btn-success mr-5", type: "button" %>
          <%#= link_to "注文履歴一覧を見る", admin_orders_path, class: "btn btn-info", type: "button" %>
        </td>
      </tr>
    </table>
  </div>
</div>