config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'orders/index'
    get 'orders/show'
  end
#public/cart_itemのアクションを追加した===================================
  namespace :public do
    resources :cart_items, only: [:index, :create, :update, :destroy] do
        collection do
            delete 'destroy_all'
        end
    end
  end
  #=======================================================================
  devise_for :customers
   namespace :public do
   resources :customers, only: [:show,:update,:index] do
       collection do
        get :edit
        get 'unsubscribe'
        patch "withdrawal"
       end
   end
 end

 devise_for :admins, controllers: {
  sessions: 'admin/sessions'
}

  namespace :admin do
    resources :customers, only: [:index,:show,:edit,:update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 namespace :public do
  resources :deliveries, only: [:create, :index, :edit, :update, :destroy]
  get 'about' => 'homes#about'
   resources :items, only: [:index, :show]
 end
 root to: 'public/homes#top'
   # 会員側のルーティング設定

  # 管理者側のルーティング設定
  namespace :admin do
    resources :items, only: [:index, :show, :new, :create, :edit, :update]
    resources :genre, only: [:index, :edit, :create, :update]
    resources :order_details, only: [:update]
  end

 namespace :public do
     resources :orders, only: [:index, :show, :new, :create]
      get 'log' => 'orders#log'

     post 'log' => 'orders#log'

     get 'thanks' => 'orders#thanks'
    end

   namespace :admin do
     resources :orders, only: [:show, :update, :index]
   end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details, dependent: :destroy
  enum payment: {
    クレジットカード: 0,
    銀行振込: 1
  }

  enum order_status:{
    pending: 0, 
    confirm: 1, 
    processing: 2,
    preparing: 3, 
    shipped: 4
    
  }
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
 before_action :authenticate_admin!
  def index
    @orders = Order.page(params[:page]).reverse_order.per(10)
    #@total_quantity = @order_quantity.sum{order_item.amount}
    @count =0
  end


  def show
    @order = Order.find(params[:id])
    @order_details = OrderDetail.all

  end

  def update
    @order = Order.find(params[:id])
    if  @order = Order.find(params[:id])
        @order.update(order_params)
        redirect_to admin_orders_path
    else
      render :show
    end
  end


  private
  def order_params
    params.require(:order).permit(:name, :address, :postal_code, :payment, :customer_id, :shipping, :total, :order_status)
  end

  def order_detail_params
    params.require(:order_detail).permit(:quantity, :make_status, :price)
  end

end

# @order.update(order_params) && @order.confirm_deposit?
        # @order.order_details.update_all(order_status: 0)
      # redirect_to admin_order_path(@order)

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admin/orders/index.html.erb
<div class="container">
  <div class="row">
    <div class="title">
      <h3>注文履歴一覧</h3>
    </div>
    <div class="col-md-12">
      <table class="table table-bordered table-hober">
        <thead>
          <th class="border-dark">購入日時</th>
          <th class="border-dark">購入者</th>
          <th class="border-dark">注文個数</th>
          <th class="border-dark">注文ステータス</th>
        </thead>
        <tbody>
          <% @orders.each do |order| %>
          <tr>
            <td class="border-dark">
              <%= link_to order.created_at.strftime("%Y/%m/%d %H:%M:%S") , admin_order_path(order.id), class: "color:black;" %>
            </td>
            <td class="border-dark">
              <%= order.name %>
            </td>
            <td class="border-dark">
              <% order.order_details.each do |order_detail| %>
                <% (@count += order_detail.quantity) %>
              <% end %>
              <%= @count %>
            </td>
            <td class="border-dark">
              <%= order.order_status_i18n %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="paging">
    <%= paginate @orders %>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8">
      <p class="title"><h4>注文履歴詳細</h4></p>
      <table class="table table-bordered table-hober">
        <tbody>
      <tr>
        <th class="border-dark" style="width: 15%"><strong>購入者</strong></th>
        <td class="border-dark"><%= link_to @order.customer.last_name + @order.customer.first_name, admin_customer_path(@order.customer.id) %></td>
      </tr>
      <tr>
        <td class="border-dark"><strong>注文日</strong></td>
        <td class="border-dark"><%= @order.created_at.strftime('%Y/%m/%d') %></td>
      </tr>
      <tr>
        <td class="border-dark"><strong>配送先</strong></td>
        <td class="border-dark">〒<%= @order.postal_code %> <%= @order.address %><br><%= @order.name %></td>
      </tr>
      <tr>
        <td class="border-dark"><strong>支払方法</strong></td>
        <td class="border-dark"><%= @order.payment_i18n %></td>
      </tr>
      <tr>
        <td class="border-dark"><strong>注文ステータス</strong></td>
        <td class="border-dark">
          <%= form_with model: @order, url: admin_order_path(@order), local: true do |f| %>
            <%= f.select :order_status, Order.order_statuses.keys.map {|k| [I18n.t("enums.order.order_status.#{k}"), k]} %>
          <%= f.submit "更新", class: 'btn btn-light btn-sm ' %>
          <% end %>
        </td>
      </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-md-8">
      <table class="table table-bordered table-hober table-inverse" >
        <thead>
          <tr class="table-active">
            <th class="border-dark" style="width:30%">商品名</th>
            <th class="border-dark" style="width:20%">単価(税込)</th>
            <th class="border-dark" style="width:10%">数量</th>
            <th class="border-dark" style="width:10%">小計</th>
            <th class="border-dark" style="width:30%">製作ステータス</th>
          </tr>
        </thead>
            <% @order.order_details.each do |order_detail| %>
          <tbody>
            <tr>
              <td class="border-dark"><%= order_detail.item.name %></td>
              <td class="border-dark"><%= order_detail.item.price.to_s(:delimited) %></td>
              <td class="border-dark"><%= order_detail.quantity %></td>
              <td class="border-dark"><%= order_detail.order.total.to_s(:delimited) %></td>
              <td class="border-dark">
                <%= form_with model: order_detail, url: admin_order_detail_path(@order,order_detail) , local: true do |f| %>
                  <%= f.select :create_status, OrderDetail.create_statuses.keys.map {|k| [I18n.t("enums.order_detail.create_status.#{k}"), k]} %>
                <%= f.submit "更新", class: 'btn btn-light btn-sm ' %>
                <% end %>
              </td>
              <td></td>
            </tr>
            <% end %>
          </tbody>
      </table>
    </div>

    <div class="col-md-3">
      <table class="table table-bordered table-hober">
        <tr>
          <td class="border-dark"><strong>商品合計</strong></td>
          <td class="border-dark"><%= (@order.total).to_s(:delimited) %>円</td>
        </tr>
        <tr>
          <td class="border-dark"><strong>送料</strong></td>
          <td class="border-dark">800円</td>
        </tr>
        <tr>
          <td class="border-dark"><strong>請求金額合計</strong></td>
          <td class="border-dark"><%= (@order.total + 800).to_s(:delimited) %>円</td>
        </tr>
      </table>
    </div>
  </div>
</div>