config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    get 'orders/index'
    get 'orders/show'
  end
#public/cart_itemのアクションを追加した===================================
  namespace :public do
    resources :cart_items, only: [:index, :create, :update, :destroy] do
        collection do
            delete 'destroy_all'
        end
    end
  end
  #=======================================================================
  devise_for :customers
   namespace :public do
   resources :customers, only: [:show,:update,:index] do
       collection do
        get :edit
        get 'unsubscribe'
        patch "withdrawal"
       end
   end
 end

 devise_for :admins, controllers: {
  sessions: 'admin/sessions'
}

  namespace :admin do
    resources :customers, only: [:index,:show,:edit,:update]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 namespace :public do
  resources :deliveries, only: [:create, :index, :edit, :update, :destroy]
  get 'about' => 'homes#about'
   resources :items, only: [:index, :show]
 end
 root to: 'public/homes#top'
   # 会員側のルーティング設定

  # 管理者側のルーティング設定
  namespace :admin do
    resources :items, only: [:index, :show, :new, :create, :edit, :update]
    resources :genre, only: [:index, :edit, :create, :update]
    resources :order_details, only: [:update]
  end

 namespace :public do
     resources :orders, only: [:index, :show, :new, :create]
      get 'log' => 'orders#log'

     post 'log' => 'orders#log'

     get 'thanks' => 'orders#thanks'
    end

   namespace :admin do
     resources :orders, only: [:show, :update, :index]
   end
end

app/views/layouts/_footer.html.erb
<div class="footer　fixed-bottom">
   <div class='container mt-5'>
    <div class='row'>
      <div class='mx-auto'>
        <p>CopyRight GAR.inc</p>
      </div>
    </div>
  </div>

app/views/layouts/_header.html.erb
<header>
 <nav class="navbar navbar-expand-lg header" >
    <div class="container">
     <a class="navbar-brand p-3" href="/"><%= image_tag('logo.png') %></a>
      <%#= link_to "Nagano cake", root_path, class: "navbar-brand" %>
      <nav>
        <ul class="nav nav-pills">
         <% if customer_signed_in? %>
          <li class="nav-item"><%= link_to "マイページ", public_customer_path(current_customer), class: "fas fa-id-card" %></li>
          <li class="nav-item"><%= link_to "商品一覧", public_items_path, class: "fas fa-door-open" %></li>
          <li class="nav-item"><%= link_to "カート", public_cart_items_path, class: "fas fa-shopping-cart" %></li>
          <li class="nav-item"><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'fas fa-sign-out-alt' %></li>
          <% elsif admin_signed_in? %>
          <li class="nav-item"><%= link_to " 商品一覧", admin_items_path, class: 'fas fa-cheese' %></li>
          <li class="nav-item"><%= link_to " 会員一覧", admin_customers_path, class: "fas fa-grin-beam" %></li>
          <li class="nav-item"><%= link_to " 注文履歴一覧", admin_orders_path, class: "fas fa-dolly-flatbed" %></li>
          <li class="nav-item"><%= link_to " ジャンル一覧", admin_genre_index_path, class: "fas fa-file-alt" %></li>
          <li class="nav-item"><%= link_to " ログアウト", destroy_admin_session_path, method: :delete, class: "fas fa-sign-out-alt" %></li>
          <% else %>
          <li class="nav-item"><%= link_to " About", public_about_path, class: "fas fa-book" %></li>
          <li class="nav-item"><%= link_to " 商品一覧", public_items_path, class: 'fas fa-cheese' %></li>
          <li class="nav-item"><%= link_to " 新規登録", new_customer_registration_path, class: "fas fa-user" %></li>
          <li class="nav-item"><%= link_to " ログイン", new_customer_session_path, class: "fas fa-sign-in-alt" %></li>
          <% end %>
        </ul>
      </nav>
    </div>
 </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charaset="UTF-8" />
    
    <script src="https://kit.fontawesome.com/126ca43df6.js" crossorigin="anonymous"></script>
    <title>NaganoCake</title>

    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header'%>
    <main>
     <%= yield %>
    </main>
     <%= render 'layouts/footer'%>
  </body>

</html>